apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world2
  template:
    metadata:
      labels:
        app: hello-world2
    spec:
    
      containers:
      - name: hello-world-container
        image: salajmi/hello-world-app:latest 
        ports:
        - containerPort: 80
